-- Autogenerated by migration tool on 2022-04-11 10:42:49

-- Resource: AccessBindingsByCloud
DROP TABLE IF EXISTS yandex_access_bindings_by_cloud;

-- Resource: AccessBindingsByFolder
DROP TABLE IF EXISTS yandex_access_bindings_by_folder;

-- Resource: AccessBindingsByOrganization
DROP TABLE IF EXISTS yandex_access_bindings_by_organization;

-- Resource: CertificateManagerCertificates
DROP TABLE IF EXISTS yandex_certificatemanager_certificate_challenges;
DROP TABLE IF EXISTS yandex_certificatemanager_certificates;

-- Resource: ComputeDisks
DROP TABLE IF EXISTS yandex_compute_disks;

-- Resource: ComputeImages
DROP TABLE IF EXISTS yandex_compute_images;

-- Resource: ComputeInstances
DROP TABLE IF EXISTS yandex_compute_instance_secondary_disks;
DROP TABLE IF EXISTS yandex_compute_instance_local_disks;
DROP TABLE IF EXISTS yandex_compute_instance_filesystems;
DROP TABLE IF EXISTS yandex_compute_instance_net_interface_ipv4_1_1_nat_dns_records;
DROP TABLE IF EXISTS yandex_compute_instance_net_interface_ipv4_dns_records;
DROP TABLE IF EXISTS yandex_compute_instance_net_interface_ipv6_1_1_nat_dns_records;
DROP TABLE IF EXISTS yandex_compute_instance_net_interface_ipv6_dns_records;
DROP TABLE IF EXISTS yandex_compute_instance_network_interfaces;
DROP TABLE IF EXISTS yandex_compute_instance_placement_policy_host_affinity_rules;
DROP TABLE IF EXISTS yandex_compute_instances;

-- Resource: IAMServiceAccounts
DROP TABLE IF EXISTS yandex_iam_service_accounts;

-- Resource: IAMUserAccountsByCloud
DROP TABLE IF EXISTS yandex_iam_user_accounts_by_cloud;

-- Resource: IAMUserAccountsByFolder
DROP TABLE IF EXISTS yandex_iam_user_accounts_by_folder;

-- Resource: IAMUserAccountsByOrganization
DROP TABLE IF EXISTS yandex_iam_user_accounts_by_organization;

-- Resource: K8SClusters
DROP TABLE IF EXISTS yandex_k8s_clusters;

-- Resource: KMSSymmetricKeys
DROP TABLE IF EXISTS yandex_kms_symmetric_keys;

-- Resource: ObjectStorageBuckets
DROP TABLE IF EXISTS yandex_object_bucket_serv_side_encrypt_config_rules;
DROP TABLE IF EXISTS yandex_object_storage_buckets;

-- Resource: ResourceManagerClouds
DROP TABLE IF EXISTS yandex_resourcemanager_clouds;

-- Resource: ResourceManagerFolders
DROP TABLE IF EXISTS yandex_resourcemanager_folders;

-- Resource: ServerlessApiGateways
DROP TABLE IF EXISTS yandex_apigateway_api_gateway_attached_domains;
DROP TABLE IF EXISTS yandex_serverless_api_gateways;

-- Resource: VPCAddresses
DROP TABLE IF EXISTS yandex_vpc_addresses;

-- Resource: VPCNetworks
DROP TABLE IF EXISTS yandex_vpc_networks;

-- Resource: VPCSecurityGroups
DROP TABLE IF EXISTS yandex_vpc_security_group_rules;
DROP TABLE IF EXISTS yandex_vpc_security_groups;

-- Resource: VPCSubnets
DROP TABLE IF EXISTS yandex_vpc_subnets;
