// Code generated by codegen; DO NOT EDIT.

package resourcemanager

import (
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
)

func Clouds() *schema.Table {
	return &schema.Table{
		Name:      "yandex_resourcemanager_clouds",
		Resolver:  fetchClouds,
		Multiplex: client.MultiplexBy(client.Clouds),
		Columns: []schema.Column{
			{
				Name:        "id",
				Type:        schema.TypeString,
				Resolver:    schema.PathResolver("Id"),
				Description: `Resource ID`,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "created_at",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("CreatedAt"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "organization_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("OrganizationId"),
			},
			{
				Name:     "labels",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Labels"),
			},
		},

		Relations: []*schema.Table{
			Folders(),
		},
	}
}
