// Code generated by yandex cloud generator; DO NOT EDIT.

package resources

import (
	"context"

	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
	"github.com/yandex-cloud/go-genproto/yandex/cloud/k8s/v1"
)

func K8SClusters() *schema.Table {
	return &schema.Table{
		Name:         "yandex_k8s_clusters",
		Resolver:     fetchK8SClusters,
		Multiplex:    client.FolderMultiplex,
		IgnoreError:  client.IgnoreErrorHandler,
		DeleteFilter: client.DeleteFolderFilter,
		Columns: []schema.Column{
			{
				Name:        "id",
				Type:        schema.TypeString,
				Description: "ID of the cluster.",
				Resolver:    client.ResolveResourceId,
			},
			{
				Name:        "folder_id",
				Type:        schema.TypeString,
				Description: "ID of the folder that the cluster belongs to.",
				Resolver:    client.ResolveFolderID,
			},
			{
				Name:        "created_at",
				Type:        schema.TypeTimestamp,
				Description: "",
				Resolver:    client.ResolveAsTime,
			},
			{
				Name:        "name",
				Type:        schema.TypeString,
				Description: "Name of the Kubernetes cluster.",
				Resolver:    schema.PathResolver("Name"),
			},
			{
				Name:        "description",
				Type:        schema.TypeString,
				Description: "Description of the Kubernetes cluster. 0-256 characters long.",
				Resolver:    schema.PathResolver("Description"),
			},
			{
				Name:        "labels",
				Type:        schema.TypeJSON,
				Description: "Resource labels as `key:value` pairs. Maximum of 64 per resource.",
				Resolver:    client.ResolveLabels,
			},
			{
				Name:        "status",
				Type:        schema.TypeString,
				Description: "Status of the Kubernetes cluster.",
				Resolver:    client.EnumPathResolver("Status"),
			},
			{
				Name:        "health",
				Type:        schema.TypeString,
				Description: "Health of the Kubernetes cluster.",
				Resolver:    client.EnumPathResolver("Health"),
			},
			{
				Name:        "network_id",
				Type:        schema.TypeString,
				Description: "ID of the network the Kubernetes cluster belongs to.",
				Resolver:    schema.PathResolver("NetworkId"),
			},
			{
				Name:        "ip_allocation_policy_cluster_ipv_4_cidr_block",
				Type:        schema.TypeString,
				Description: "CIDR block. IP range for allocating pod addresses.\n\n It should not overlap with any subnet in the network the Kubernetes cluster located in. Static routes will be\n set up for this CIDR blocks in node subnets.",
				Resolver:    schema.PathResolver("IpAllocationPolicy.ClusterIpv4CidrBlock"),
			},
			{
				Name:        "ip_allocation_policy_node_ipv_4_cidr_mask_size",
				Type:        schema.TypeBigInt,
				Description: "Size of the masks that are assigned for each node in the cluster.\n\n If not specified, 24 is used.",
				Resolver:    schema.PathResolver("IpAllocationPolicy.NodeIpv4CidrMaskSize"),
			},
			{
				Name:        "ip_allocation_policy_service_ipv_4_cidr_block",
				Type:        schema.TypeString,
				Description: "CIDR block. IP range Kubernetes service Kubernetes cluster IP addresses will be allocated from.\n\n It should not overlap with any subnet in the network the Kubernetes cluster located in.",
				Resolver:    schema.PathResolver("IpAllocationPolicy.ServiceIpv4CidrBlock"),
			},
			{
				Name:        "ip_allocation_policy_cluster_ipv_6_cidr_block",
				Type:        schema.TypeString,
				Description: "IPv6 range for allocating pod IP addresses.",
				Resolver:    schema.PathResolver("IpAllocationPolicy.ClusterIpv6CidrBlock"),
			},
			{
				Name:        "ip_allocation_policy_service_ipv_6_cidr_block",
				Type:        schema.TypeString,
				Description: "IPv6 range for allocating Kubernetes service IP addresses",
				Resolver:    schema.PathResolver("IpAllocationPolicy.ServiceIpv6CidrBlock"),
			},
			{
				Name:        "internet_gateway_gateway_ipv_4_address",
				Type:        schema.TypeString,
				Description: "Gateway IPv4 address.",
				Resolver:    schema.PathResolver("InternetGateway.GatewayIpv4Address"),
			},
			{
				Name:        "service_account_id",
				Type:        schema.TypeString,
				Description: "Service account to be used for provisioning Compute Cloud and VPC resources for Kubernetes cluster.",
				Resolver:    schema.PathResolver("ServiceAccountId"),
			},
			{
				Name:        "node_service_account_id",
				Type:        schema.TypeString,
				Description: "Service account to be used by the worker nodes of the Kubernetes cluster to access Container Registry or to push node logs and metrics.",
				Resolver:    schema.PathResolver("NodeServiceAccountId"),
			},
			{
				Name:        "release_channel",
				Type:        schema.TypeString,
				Description: "When creating a Kubernetes cluster, you should specify one of three release channels. The release channel contains several Kubernetes versions.\n Channels differ in the set of available versions, the management of auto-updates, and the updates received.\n You can't change the channel once the Kubernetes cluster is created, you can only recreate the Kubernetes cluster and specify a new release channel.\n For more details see [documentation](https://cloud.yandex.com/docs/managed-kubernetes/concepts/release-channels-and-updates).",
				Resolver:    client.EnumPathResolver("ReleaseChannel"),
			},
			{
				Name:        "network_policy_provider",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    client.EnumPathResolver("NetworkPolicy.Provider"),
			},
			{
				Name:        "kms_provider_key_id",
				Type:        schema.TypeString,
				Description: "KMS key ID for secrets encryption.\n To obtain a KMS key ID use a [yandex.cloud.kms.v1.SymmetricKeyService.List] request.",
				Resolver:    schema.PathResolver("KmsProvider.KeyId"),
			},
			{
				Name:        "log_group_id",
				Type:        schema.TypeString,
				Description: "Log group where cluster stores cluster system logs, like audit, events, or controlplane logs.",
				Resolver:    schema.PathResolver("LogGroupId"),
			},
			{
				Name:        "network_implementation_cilium_routing_mode",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    client.EnumPathResolver("NetworkImplementation.Cilium.RoutingMode"),
			},
		},
	}

}

func fetchK8SClusters(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan interface{}) error {
	c := meta.(*client.Client)

	locations := []string{c.FolderId}

	for _, f := range locations {
		req := &k8s.ListClustersRequest{FolderId: f}
		it := c.Services.K8S.Cluster().ClusterIterator(ctx, req)
		for it.Next() {
			res <- it.Value()
		}
	}

	return nil
}
