// Code generated by yandex cloud generator; DO NOT EDIT.

package resources_test

import (
	"context"
	"errors"
	"fmt"
	"net"
	"testing"

	"google.golang.org/grpc"

	"github.com/cloudquery/cq-provider-sdk/logging"
	"github.com/cloudquery/cq-provider-sdk/provider/providertest"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/cloudquery/faker/v3"
	"github.com/hashicorp/go-hclog"
	"github.com/yandex-cloud/cq-provider-yandex/client"
	"github.com/yandex-cloud/cq-provider-yandex/resources"
	resourcemanager1 "github.com/yandex-cloud/go-genproto/yandex/cloud/resourcemanager/v1"
	"github.com/yandex-cloud/go-sdk/gen/resourcemanager"
)

func TestResourceManagerClouds(t *testing.T) {
	resourcemanagerSvc, serv, err := createCloudServer()
	if err != nil {
		t.Fatal(err)
	}
	resource := providertest.ResourceTestData{
		Table: resources.ResourceManagerClouds(),
		Config: client.Config{
			CloudIDs: []string{"test"},
		},
		Configure: func(logger hclog.Logger, _ interface{}) (schema.ClientMeta, error) {
			c := client.NewYandexClient(
				logging.New(&hclog.LoggerOptions{
					Level: hclog.Warn,
				}),
				nil,
				[]string{"test"},
				nil,
				&client.Services{
					ResourceManager: resourcemanagerSvc,
				}, nil)
			return c, nil
		},
		Verifiers: []providertest.Verifier{
			providertest.VerifyAtLeastOneRow("yandex_resourcemanager_clouds"),
		},
	}
	providertest.TestResource(t, resources.Provider, resource)
	serv.Stop()
}

type FakeCloudServiceServer struct {
	resourcemanager1.UnimplementedCloudServiceServer
	Cloud *resourcemanager1.Cloud
}

func NewFakeCloudServiceServer() (*FakeCloudServiceServer, error) {
	var cloud resourcemanager1.Cloud
	faker.SetIgnoreInterface(true)
	err := faker.FakeData(&cloud)
	if err != nil {
		return nil, err
	}
	cloud.Name = "test"
	return &FakeCloudServiceServer{Cloud: &cloud}, nil
}

func (s *FakeCloudServiceServer) Get(_ context.Context, req *resourcemanager1.GetCloudRequest) (*resourcemanager1.Cloud, error) {
	if req.CloudId == "test" {
		return s.Cloud, nil
	}
	return nil, errors.New("no such Cloud")
}

func createCloudServer() (*resourcemanager.ResourceManager, *grpc.Server, error) {
	lis, err := net.Listen("tcp", ":0")

	if err != nil {
		return nil, nil, err
	}

	serv := grpc.NewServer()
	fakeCloudServiceServer, err := NewFakeCloudServiceServer()

	if err != nil {
		return nil, nil, err
	}

	resourcemanager1.RegisterCloudServiceServer(serv, fakeCloudServiceServer)

	go func() {
		err := serv.Serve(lis)
		if err != nil {
			fmt.Println(err.Error())
		}
	}()

	conn, err := grpc.Dial(lis.Addr().String(), grpc.WithInsecure())

	if err != nil {
		return nil, nil, err
	}

	return resourcemanager.NewResourceManager(
		func(ctx context.Context) (*grpc.ClientConn, error) {
			return conn, nil
		},
	), serv, nil
}
