// Code generated by cq-provider-yandex resource generator; DO NOT EDIT.

package resources

import (
	"context"

	"github.com/thoas/go-funk"

	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
	"github.com/yandex-cloud/go-genproto/yandex/cloud/vpc/v1"
)

func VPCSecurityGroups() *schema.Table {
	return &schema.Table{
		Name:         "yandex_vpc_security_groups",
		Resolver:     fetchVPCSecurityGroups,
		Multiplex:    client.MultiplexBy(client.Folders),
		IgnoreError:  client.IgnoreErrorHandler,
		DeleteFilter: client.DeleteFolderFilter,
		Columns: []schema.Column{
			{
				Name:            "id",
				Type:            schema.TypeString,
				Description:     "ID of the resource.",
				Resolver:        client.ResolveResourceId,
				CreationOptions: schema.ColumnCreationOptions{NotNull: !false, Unique: true},
			},
			{
				Name:        "folder_id",
				Type:        schema.TypeString,
				Description: "ID of the folder that the resource belongs to.",
				Resolver:    client.ResolveFolderID,
			},
			{
				Name:        "created_at",
				Type:        schema.TypeTimestamp,
				Description: "",
				Resolver:    client.ResolveAsTime,
			},
			{
				Name:        "name",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    schema.PathResolver("Name"),
			},
			{
				Name:        "description",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    schema.PathResolver("Description"),
			},
			{
				Name:        "labels",
				Type:        schema.TypeJSON,
				Description: "Resource labels as `key:value` pairs. Maximum of 64 per resource.",
				Resolver:    client.ResolveLabels,
			},
			{
				Name:        "network_id",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    schema.PathResolver("NetworkId"),
			},
			{
				Name:        "status",
				Type:        schema.TypeString,
				Description: "",
				Resolver:    client.EnumPathResolver("Status"),
			},
			{
				Name:        "default_for_network",
				Type:        schema.TypeBool,
				Description: "",
				Resolver:    schema.PathResolver("DefaultForNetwork"),
			},
		},

		Relations: []*schema.Table{
			{
				Name:        "yandex_vpc_security_group_rules",
				Resolver:    fetchVPCSecurityGroupRules,
				Multiplex:   client.EmptyMultiplex,
				IgnoreError: client.IgnoreErrorHandler,
				Columns: []schema.Column{
					{
						Name:        "security_group_cq_id",
						Type:        schema.TypeUUID,
						Description: "cq_id of parent security_group",
						Resolver:    schema.ParentIdResolver,
					},
					{
						Name:        "security_group_id",
						Type:        schema.TypeString,
						Description: "id of parent security_group",
						Resolver:    schema.ParentResourceFieldResolver("id"),
					},
					{
						Name:            "id",
						Type:            schema.TypeString,
						Description:     "",
						Resolver:        schema.PathResolver("Id"),
						CreationOptions: schema.ColumnCreationOptions{NotNull: !false, Unique: true},
					},
					{
						Name:        "description",
						Type:        schema.TypeString,
						Description: "",
						Resolver:    schema.PathResolver("Description"),
					},
					{
						Name:        "labels",
						Type:        schema.TypeJSON,
						Description: "",
						Resolver:    schema.PathResolver("Labels"),
					},
					{
						Name:        "direction",
						Type:        schema.TypeString,
						Description: "",
						Resolver:    client.EnumPathResolver("Direction"),
					},
					{
						Name:        "ports_from_port",
						Type:        schema.TypeBigInt,
						Description: "",
						Resolver:    schema.PathResolver("Ports.FromPort"),
					},
					{
						Name:        "ports_to_port",
						Type:        schema.TypeBigInt,
						Description: "",
						Resolver:    schema.PathResolver("Ports.ToPort"),
					},
					{
						Name:        "protocol_name",
						Type:        schema.TypeString,
						Description: "null value means any protocol\n values from https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml",
						Resolver:    schema.PathResolver("ProtocolName"),
					},
					{
						Name:        "protocol_number",
						Type:        schema.TypeBigInt,
						Description: "",
						Resolver:    schema.PathResolver("ProtocolNumber"),
					},
					{
						Name:        "target_cidr_blocks_v_4_cidr_blocks",
						Type:        schema.TypeStringArray,
						Description: "",
						Resolver:    schema.PathResolver("Target.CidrBlocks.V4CidrBlocks"),
					},
					{
						Name:        "target_cidr_blocks_v_6_cidr_blocks",
						Type:        schema.TypeStringArray,
						Description: "",
						Resolver:    schema.PathResolver("Target.CidrBlocks.V6CidrBlocks"),
					},
					{
						Name:        "target_security_group_id",
						Type:        schema.TypeString,
						Description: "",
						Resolver:    schema.PathResolver("Target.SecurityGroupId"),
					},
					{
						Name:        "target_predefined_target",
						Type:        schema.TypeString,
						Description: "",
						Resolver:    schema.PathResolver("Target.PredefinedTarget"),
					},
				},
			},
		},
	}

}

func fetchVPCSecurityGroups(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)

	req := &vpc.ListSecurityGroupsRequest{FolderId: c.MultiplexedResourceId}
	it := c.Services.VPC.SecurityGroup().SecurityGroupIterator(ctx, req)
	for it.Next() {
		res <- it.Value()
	}

	return nil
}

func fetchVPCSecurityGroupRules(_ context.Context, _ schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
	values := funk.Get(parent.Item, "Rules")

	if funk.IsIteratee(values) {
		funk.ForEach(values, func(value interface{}) {
			res <- value
		})
	}

	return nil
}
