// Code generated by yandex cloud generator; DO NOT EDIT.

package resources

import (
	"context"

	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
	"github.com/yandex-cloud/go-genproto/yandex/cloud/vpc/v1"
)

func VPCAddresses() *schema.Table {
	return &schema.Table{
		Name:         "yandex_vpc_addresses",
		Resolver:     fetchVPCAddresses,
		Multiplex:    client.FolderMultiplex,
		IgnoreError:  client.IgnoreErrorHandler,
		DeleteFilter: client.DeleteFolderFilter,
		Columns: []schema.Column{
			{
				Name:        "address_id",
				Type:        schema.TypeString,
				Description: "ID of the address.",
				Resolver:    client.ResolveResourceId,
			},
			{
				Name:        "folder_id",
				Type:        schema.TypeString,
				Description: "ID of the folder that the address belongs to.",
				Resolver:    client.ResolveFolderID,
			},
			{
				Name:        "created_at",
				Type:        schema.TypeTimestamp,
				Description: "",
				Resolver:    client.ResolveAsTime,
			},
			{
				Name:        "name",
				Type:        schema.TypeString,
				Description: "Name of the address.\n The name is unique within the folder.",
				Resolver:    schema.PathResolver("Name"),
			},
			{
				Name:        "description",
				Type:        schema.TypeString,
				Description: "Description of the address.",
				Resolver:    schema.PathResolver("Description"),
			},
			{
				Name:        "labels",
				Type:        schema.TypeJSON,
				Description: "Resource labels as `key:value` pairs. Maximum of 64 per resource.",
				Resolver:    client.ResolveLabels,
			},
			{
				Name:        "reserved",
				Type:        schema.TypeBool,
				Description: "Specifies if address is reserved or not.",
				Resolver:    schema.PathResolver("Reserved"),
			},
			{
				Name:        "used",
				Type:        schema.TypeBool,
				Description: "Specifies if address is used or not.",
				Resolver:    schema.PathResolver("Used"),
			},
			{
				Name:        "type",
				Type:        schema.TypeString,
				Description: "Type of the IP address.",
				Resolver:    client.EnumPathResolver("Type"),
			},
			{
				Name:        "ip_version",
				Type:        schema.TypeString,
				Description: "Vervion of the IP address.",
				Resolver:    client.EnumPathResolver("IpVersion"),
			},
		},
	}

}

func fetchVPCAddresses(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan interface{}) error {
	c := meta.(*client.Client)

	locations := []string{c.FolderId}

	for _, f := range locations {
		req := &vpc.ListAddressesRequest{FolderId: f}
		it := c.Services.VPC.Address().AddressIterator(ctx, req)
		for it.Next() {
			res <- it.Value()
		}
	}

	return nil
}
