package plugin

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// Every top-level table needs a multiplexer, even one whose RPC takes no
// folder, cloud or organization: the multiplexer is what declares the service
// the table needs, and a table without one is synced in every region whether
// the installation offers that service or not. Global tables use
// client.GlobalMultiplex. Relations inherit the client of their parent and are
// deliberately not checked.
func TestTopLevelTablesDeclareAService(t *testing.T) {
	for _, table := range PluginAutoGeneratedTables() {
		assert.NotNil(t, table.Multiplex, "table %q has no Multiplex", table.Name)
	}
}
