package plugin

import (
	"maps"
	"strings"

	"github.com/cloudquery/plugin-sdk/v4/caser"
	"github.com/cloudquery/plugin-sdk/v4/docs"
	"github.com/cloudquery/plugin-sdk/v4/schema"
	"github.com/cloudquery/plugin-sdk/v4/transformers"
	"github.com/yandex-cloud/cq-source-yc/resources/access"
	"github.com/yandex-cloud/cq-source-yc/resources/ai/assistants"
	"github.com/yandex-cloud/cq-source-yc/resources/ai/batchinference"
	"github.com/yandex-cloud/cq-source-yc/resources/ai/datasets"
	aifiles "github.com/yandex-cloud/cq-source-yc/resources/ai/files"
	"github.com/yandex-cloud/cq-source-yc/resources/ai/tuning"
	"github.com/yandex-cloud/cq-source-yc/resources/alb"
	"github.com/yandex-cloud/cq-source-yc/resources/audittrails"
	"github.com/yandex-cloud/cq-source-yc/resources/baremetal"
	"github.com/yandex-cloud/cq-source-yc/resources/cdn"
	"github.com/yandex-cloud/cq-source-yc/resources/cic"
	"github.com/yandex-cloud/cq-source-yc/resources/cloudregistry"
	"github.com/yandex-cloud/cq-source-yc/resources/compute"
	"github.com/yandex-cloud/cq-source-yc/resources/containerregistry"
	"github.com/yandex-cloud/cq-source-yc/resources/datasphere"
	"github.com/yandex-cloud/cq-source-yc/resources/datatransfer"
	"github.com/yandex-cloud/cq-source-yc/resources/dns"
	"github.com/yandex-cloud/cq-source-yc/resources/iam"
	"github.com/yandex-cloud/cq-source-yc/resources/kms"
	"github.com/yandex-cloud/cq-source-yc/resources/kubernetes"
	"github.com/yandex-cloud/cq-source-yc/resources/lockbox"
	"github.com/yandex-cloud/cq-source-yc/resources/mdb"
	"github.com/yandex-cloud/cq-source-yc/resources/nlb"
	"github.com/yandex-cloud/cq-source-yc/resources/organizationmanager"
	"github.com/yandex-cloud/cq-source-yc/resources/quotamanager"
	"github.com/yandex-cloud/cq-source-yc/resources/resourcemanager"
	"github.com/yandex-cloud/cq-source-yc/resources/serverless"
	"github.com/yandex-cloud/cq-source-yc/resources/serverless/eventrouter"
	"github.com/yandex-cloud/cq-source-yc/resources/serverless/triggers"
	"github.com/yandex-cloud/cq-source-yc/resources/serverless/workflows"
	"github.com/yandex-cloud/cq-source-yc/resources/storage"
	"github.com/yandex-cloud/cq-source-yc/resources/trino"
	"github.com/yandex-cloud/cq-source-yc/resources/vpc"
	"github.com/yandex-cloud/cq-source-yc/resources/vpc/privatelink"
	"github.com/yandex-cloud/cq-source-yc/resources/ydb"
)

var ycExceptions = map[string]string{
	"ai":                  "AI",
	"alb":                 "Application Load Balancer",
	"apigateway":          "API Gateway",
	"apigateways":         "API Gateways",
	"audittrails":         "Audit Trails",
	"cdn":                 "CDN",
	"cic":                 "Interconnect",
	"cloudregistry":       "Registry",
	"compute":             "Compute",
	"containerregistry":   "Container Registry",
	"datasphere":          "DataSphere",
	"datatransfer":        "Data Transfer",
	"iam":                 "IAM",
	"kms":                 "Key Management Service",
	"mdb":                 "Managed Service for",
	"nlb":                 "Network Load Balancer",
	"organizationmanager": "Cloud Organization",
	"quotamanager":        "Quota Manager",
	"resourcemanager":     "Resource Manager",
	"storage":             "Object Storage",
	"vrfs":                "VRFs",
	"yc":                  "YC",
	"ydb":                 "Managed Service for YDB",
}

func tableTransformer(table *schema.Table) error {
	if table.Title != "" {
		return nil
	}
	exceptions := maps.Clone(docs.DefaultTitleExceptions)
	for k, v := range ycExceptions {
		exceptions[k] = v
	}
	csr := caser.New(caser.WithCustomExceptions(exceptions))
	t := csr.ToTitle(table.Name)
	table.Title = strings.Trim(strings.ReplaceAll(t, "  ", " "), " ")
	return nil
}

func PluginAutoGeneratedTables() schema.Tables {
	tables := schema.Tables{
		// TODO: add comment explaining why resource hierarchy AB goes here and not in relations
		access.CloudsAccessBindings(),
		access.FoldersAccessBindings(),
		access.OrganizationsAccessBindings(),

		access.CloudsAccessPolicyBindings(),
		access.FoldersAccessPolicyBindings(),
		access.OrganizationsAccessPolicyBindings(),

		assistants.Assistants(),
		batchinference.BatchInferences(),
		datasets.Datasets(),
		aifiles.Files(),
		tuning.Tunings(),

		alb.Balancers(),
		audittrails.Trails(),

		baremetal.Configurations(),
		baremetal.HardwarePools(),
		baremetal.Images(),
		baremetal.PrivateCloudConnections(),
		baremetal.PrivateSubnets(),
		baremetal.PublicPrefixPools(),
		baremetal.PublicSubnets(),
		baremetal.RentalPeriods(),
		baremetal.Servers(),
		baremetal.StandardImages(),
		baremetal.Vrfs(),
		baremetal.Zones(),

		cdn.Resources(),
		cic.Partners(),
		cic.PointOfPresences(),
		cic.PrivateConnections(),
		cic.PublicConnections(),
		cic.TrunkConnections(),
		cloudregistry.Registries(),
		compute.Disks(),
		compute.Images(),
		compute.Instances(),
		containerregistry.Registries(),
		datasphere.Communities(),
		datatransfer.Endpoints(),
		datatransfer.Transfers(),
		dns.Zones(),
		iam.AccessPolicyTemplates(),
		iam.ServiceAccounts(),
		kms.AsymmetricKeys(),
		kms.SymmetricKeys(),
		kubernetes.Clusters(),
		kubernetes.NodeGroups(),
		lockbox.Secrets(),
		mdb.ClickhouseClusters(),
		mdb.GreenplumClusters(),
		mdb.KafkaClusters(),
		mdb.MongoDBClusters(),
		mdb.MySQLClusters(),
		mdb.OpenSearchClusters(),
		mdb.PostgreSQLBackups(),
		mdb.PostgreSQLClusters(),
		mdb.RedisClusters(),
		nlb.Balancers(),
		nlb.TargetGroups(),
		organizationmanager.Federations(),
		organizationmanager.Groups(),
		organizationmanager.Organizations(),
		organizationmanager.OsloginSettings(),
		organizationmanager.Users(),
		privatelink.PrivateEndpoints(),
		quotamanager.QuotaLimits(),
		quotamanager.QuotaServices(),
		resourcemanager.Clouds(),
		resourcemanager.Folders(),
		serverless.APIGatewayGateways(),
		serverless.ContainersContainers(),
		serverless.FunctionsFunctions(),
		eventrouter.Buses(),
		eventrouter.Connectors(),
		eventrouter.Rules(),
		triggers.Triggers(),
		workflows.Workflows(),
		storage.Buckets(),
		trino.Clusters(),
		vpc.Addresses(),
		vpc.Gateways(),
		vpc.Networks(),
		vpc.RouteTables(),
		vpc.SecurityGroups(),
		vpc.Subnets(),
		ydb.Databases(),
	}
	if err := transformers.TransformTables(tables); err != nil {
		panic(err)
	}

	if err := transformers.Apply(tables, tableTransformer); err != nil {
		panic(err)
	}

	for _, table := range tables {
		schema.AddCqIDs(table)
	}
	return tables
}
