// Code generated by codegen; DO NOT EDIT.

package access_bindings

import (
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
)

func ByCloud() *schema.Table {
	return &schema.Table{
		Name:      "yandex_access_bindings_by_cloud",
		Resolver:  fetchByCloud,
		Multiplex: client.MultiplexBy(client.Clouds),
		Columns: []schema.Column{
			{
				Name:     "resource_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveMultiplexedResourceID,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "role_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RoleId"),
			},
			{
				Name:     "subject_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Subject.Id"),
			},
			{
				Name:     "subject_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Subject.Type"),
			},
		},
	}
}
