// Code generated by codegen; DO NOT EDIT.

package dns

import (
	"github.com/cloudquery/plugin-sdk/schema"
)

func Records() *schema.Table {
	return &schema.Table{
		Name:     "yandex_dns_records",
		Resolver: fetchRecords,
		Columns: []schema.Column{
			{
				Name:     "zone_id",
				Type:     schema.TypeString,
				Resolver: schema.ParentColumnResolver("id"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Type"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "ttl",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("Ttl"),
			},
			{
				Name:     "data",
				Type:     schema.TypeStringArray,
				Resolver: schema.PathResolver("Data"),
			},
		},
	}
}
