// Code generated by codegen; DO NOT EDIT.

package dns

import (
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/yandex-cloud/cq-provider-yandex/client"
)

func Zones() *schema.Table {
	return &schema.Table{
		Name:      "yandex_dns_zones",
		Resolver:  fetchZones,
		Multiplex: client.MultiplexBy(client.Folders),
		Columns: []schema.Column{
			{
				Name:        "id",
				Type:        schema.TypeString,
				Resolver:    schema.PathResolver("Id"),
				Description: `Resource ID`,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "folder_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("FolderId"),
			},
			{
				Name:     "created_at",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("CreatedAt"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "labels",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Labels"),
			},
			{
				Name:     "zone",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Zone"),
			},
			{
				Name:     "private_visibility",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PrivateVisibility"),
			},
			{
				Name:     "public_visibility",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PublicVisibility"),
			},
		},

		Relations: []*schema.Table{
			Records(),
		},
	}
}
