// Package datalens provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package datalens

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	IAM_tokenScopes       iAMTokenContextKey       = "IAM_token.Scopes"
	Organization_IDScopes organizationIDContextKey = "Organization_ID.Scopes"
)

// Defines values for EntryScope.
const (
	EntryScopeArtifact   EntryScope = "artifact"
	EntryScopeCompute    EntryScope = "compute"
	EntryScopeConnection EntryScope = "connection"
	EntryScopeDash       EntryScope = "dash"
	EntryScopeDataset    EntryScope = "dataset"
	EntryScopeFolder     EntryScope = "folder"
	EntryScopeReport     EntryScope = "report"
	EntryScopeWidget     EntryScope = "widget"
)

// Valid indicates whether the value is a known member of the EntryScope enum.
func (e EntryScope) Valid() bool {
	switch e {
	case EntryScopeArtifact:
		return true
	case EntryScopeCompute:
		return true
	case EntryScopeConnection:
		return true
	case EntryScopeDash:
		return true
	case EntryScopeDataset:
		return true
	case EntryScopeFolder:
		return true
	case EntryScopeReport:
		return true
	case EntryScopeWidget:
		return true
	default:
		return false
	}
}

// Defines values for GetEntriesV2ArgsOrderByDirection.
const (
	GetEntriesV2ArgsOrderByDirectionAsc  GetEntriesV2ArgsOrderByDirection = "asc"
	GetEntriesV2ArgsOrderByDirectionDesc GetEntriesV2ArgsOrderByDirection = "desc"
)

// Valid indicates whether the value is a known member of the GetEntriesV2ArgsOrderByDirection enum.
func (e GetEntriesV2ArgsOrderByDirection) Valid() bool {
	switch e {
	case GetEntriesV2ArgsOrderByDirectionAsc:
		return true
	case GetEntriesV2ArgsOrderByDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetEntriesV2ArgsOrderByField.
const (
	GetEntriesV2ArgsOrderByFieldCreatedAt GetEntriesV2ArgsOrderByField = "createdAt"
	GetEntriesV2ArgsOrderByFieldName      GetEntriesV2ArgsOrderByField = "name"
)

// Valid indicates whether the value is a known member of the GetEntriesV2ArgsOrderByField enum.
func (e GetEntriesV2ArgsOrderByField) Valid() bool {
	switch e {
	case GetEntriesV2ArgsOrderByFieldCreatedAt:
		return true
	case GetEntriesV2ArgsOrderByFieldName:
		return true
	default:
		return false
	}
}

// Defines values for GetEntriesV2ResultEntries0IsLocked.
const (
	GetEntriesV2ResultEntries0IsLockedTrue GetEntriesV2ResultEntries0IsLocked = true
)

// Valid indicates whether the value is a known member of the GetEntriesV2ResultEntries0IsLocked enum.
func (e GetEntriesV2ResultEntries0IsLocked) Valid() bool {
	switch e {
	case GetEntriesV2ResultEntries0IsLockedTrue:
		return true
	default:
		return false
	}
}

// Defines values for GetEntriesV2ResultEntries1IsLocked.
const (
	GetEntriesV2ResultEntries1IsLockedFalse GetEntriesV2ResultEntries1IsLocked = false
)

// Valid indicates whether the value is a known member of the GetEntriesV2ResultEntries1IsLocked enum.
func (e GetEntriesV2ResultEntries1IsLocked) Valid() bool {
	switch e {
	case GetEntriesV2ResultEntries1IsLockedFalse:
		return true
	default:
		return false
	}
}

// Defines values for ListDirectoryArgsOrderByDirection.
const (
	ListDirectoryArgsOrderByDirectionAsc  ListDirectoryArgsOrderByDirection = "asc"
	ListDirectoryArgsOrderByDirectionDesc ListDirectoryArgsOrderByDirection = "desc"
)

// Valid indicates whether the value is a known member of the ListDirectoryArgsOrderByDirection enum.
func (e ListDirectoryArgsOrderByDirection) Valid() bool {
	switch e {
	case ListDirectoryArgsOrderByDirectionAsc:
		return true
	case ListDirectoryArgsOrderByDirectionDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListDirectoryArgsOrderByField.
const (
	ListDirectoryArgsOrderByFieldCreatedAt ListDirectoryArgsOrderByField = "createdAt"
	ListDirectoryArgsOrderByFieldName      ListDirectoryArgsOrderByField = "name"
)

// Valid indicates whether the value is a known member of the ListDirectoryArgsOrderByField enum.
func (e ListDirectoryArgsOrderByField) Valid() bool {
	switch e {
	case ListDirectoryArgsOrderByFieldCreatedAt:
		return true
	case ListDirectoryArgsOrderByFieldName:
		return true
	default:
		return false
	}
}

// Defines values for ApiVersionHeader.
const (
	ApiVersionHeaderN2 ApiVersionHeader = "2"
)

// Valid indicates whether the value is a known member of the ApiVersionHeader enum.
func (e ApiVersionHeader) Valid() bool {
	switch e {
	case ApiVersionHeaderN2:
		return true
	default:
		return false
	}
}

// Defines values for PostRpcGetEntriesParamsXDlApiVersion.
const (
	PostRpcGetEntriesParamsXDlApiVersionN2 PostRpcGetEntriesParamsXDlApiVersion = "2"
)

// Valid indicates whether the value is a known member of the PostRpcGetEntriesParamsXDlApiVersion enum.
func (e PostRpcGetEntriesParamsXDlApiVersion) Valid() bool {
	switch e {
	case PostRpcGetEntriesParamsXDlApiVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for PostRpcGetEntriesParamsXDlAuditMode.
const (
	PostRpcGetEntriesParamsXDlAuditModeTrue PostRpcGetEntriesParamsXDlAuditMode = "true"
)

// Valid indicates whether the value is a known member of the PostRpcGetEntriesParamsXDlAuditMode enum.
func (e PostRpcGetEntriesParamsXDlAuditMode) Valid() bool {
	switch e {
	case PostRpcGetEntriesParamsXDlAuditModeTrue:
		return true
	default:
		return false
	}
}

// Defines values for PostRpcListDirectoryParamsXDlApiVersion.
const (
	PostRpcListDirectoryParamsXDlApiVersionN2 PostRpcListDirectoryParamsXDlApiVersion = "2"
)

// Valid indicates whether the value is a known member of the PostRpcListDirectoryParamsXDlApiVersion enum.
func (e PostRpcListDirectoryParamsXDlApiVersion) Valid() bool {
	switch e {
	case PostRpcListDirectoryParamsXDlApiVersionN2:
		return true
	default:
		return false
	}
}

// EntryPermissions defines model for EntryPermissions.
type EntryPermissions struct {
	// Admin Indicates if there are permissions for admin.
	Admin bool `json:"admin"`

	// Edit Indicates if there are permissions to edit.
	Edit bool `json:"edit"`

	// Execute Indicates if there are permissions to execute.
	Execute bool `json:"execute"`

	// Read Indicates if there are permissions to read.
	Read bool `json:"read"`
}

// EntryScope Type of the entry, e.g. `dash` — dashboard, `widget` — chart, etc.
type EntryScope string

// GetEntriesV2Args defines model for GetEntriesV2Args.
type GetEntriesV2Args struct {
	CreatedBy     *[]string `json:"createdBy,omitempty"`
	ExcludeLocked *bool     `json:"excludeLocked,omitempty"`
	Filters       *struct {
		Name *string `json:"name,omitempty"`
	} `json:"filters,omitempty"`
	Ids                    *[]string `json:"ids,omitempty"`
	IgnoreSharedEntries    *bool     `json:"ignoreSharedEntries,omitempty"`
	IgnoreWorkbookEntries  *bool     `json:"ignoreWorkbookEntries,omitempty"`
	IncludeData            *bool     `json:"includeData,omitempty"`
	IncludeLinks           *bool     `json:"includeLinks,omitempty"`
	IncludePermissionsInfo *bool     `json:"includePermissionsInfo,omitempty"`
	OrderBy                *struct {
		Direction GetEntriesV2ArgsOrderByDirection `json:"direction"`
		Field     GetEntriesV2ArgsOrderByField     `json:"field"`
	} `json:"orderBy,omitempty"`
	PageSize  *int    `json:"pageSize,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`

	// Scope Type of the entry, e.g. `dash` — dashboard, `widget` — chart, etc.
	Scope *EntryScope `json:"scope,omitempty"`
	Type  *string     `json:"type,omitempty"`
}

// GetEntriesV2ArgsOrderByDirection defines model for GetEntriesV2Args.OrderBy.Direction.
type GetEntriesV2ArgsOrderByDirection string

// GetEntriesV2ArgsOrderByField defines model for GetEntriesV2Args.OrderBy.Field.
type GetEntriesV2ArgsOrderByField string

// GetEntriesV2Result defines model for GetEntriesV2Result.
type GetEntriesV2Result struct {
	Entries       []GetEntriesV2Result_Entries_Item `json:"entries"`
	NextPageToken *string                           `json:"nextPageToken,omitempty"`
}

// GetEntriesV2ResultEntries0 defines model for .
type GetEntriesV2ResultEntries0 struct {
	EntryId  string                             `json:"entryId"`
	IsLocked GetEntriesV2ResultEntries0IsLocked `json:"isLocked"`
	Name     string                             `json:"name"`

	// Scope Type of the entry, e.g. `dash` — dashboard, `widget` — chart, etc.
	Scope EntryScope `json:"scope"`
	Type  string     `json:"type"`
}

// GetEntriesV2ResultEntries0IsLocked defines model for GetEntriesV2Result.Entries.0.IsLocked.
type GetEntriesV2ResultEntries0IsLocked bool

// GetEntriesV2ResultEntries1 defines model for .
type GetEntriesV2ResultEntries1 struct {
	CollectionId    *string                             `json:"collectionId"`
	CollectionTitle *string                             `json:"collectionTitle,omitempty"`
	CreatedAt       string                              `json:"createdAt"`
	CreatedBy       string                              `json:"createdBy"`
	Data            *map[string]interface{}             `json:"data,omitempty"`
	EntryId         string                              `json:"entryId"`
	Hidden          bool                                `json:"hidden"`
	IsFavorite      bool                                `json:"isFavorite"`
	IsLocked        *GetEntriesV2ResultEntries1IsLocked `json:"isLocked,omitempty"`
	Key             string                              `json:"key"`
	Links           *map[string]string                  `json:"links"`
	Meta            *map[string]interface{}             `json:"meta"`
	Name            string                              `json:"name"`
	Permissions     *EntryPermissions                   `json:"permissions,omitempty"`
	PublishedId     *string                             `json:"publishedId"`
	SavedId         string                              `json:"savedId"`

	// Scope Type of the entry, e.g. `dash` — dashboard, `widget` — chart, etc.
	Scope         EntryScope `json:"scope"`
	Type          string     `json:"type"`
	UpdatedAt     string     `json:"updatedAt"`
	UpdatedBy     string     `json:"updatedBy"`
	WorkbookId    *string    `json:"workbookId"`
	WorkbookTitle *string    `json:"workbookTitle,omitempty"`
}

// GetEntriesV2ResultEntries1IsLocked defines model for GetEntriesV2Result.Entries.1.IsLocked.
type GetEntriesV2ResultEntries1IsLocked bool

// GetEntriesV2Result_Entries_Item defines model for GetEntriesV2Result.entries.Item.
type GetEntriesV2Result_Entries_Item struct {
	union json.RawMessage
}

// ListDirectoryArgs defines model for ListDirectoryArgs.
type ListDirectoryArgs struct {
	// CreatedBy Filter entries by creator.
	CreatedBy *ListDirectoryArgs_CreatedBy `json:"createdBy,omitempty"`

	// Filters Filtering configuration.
	Filters *struct {
		// Name Filter entries by name.
		Name *string `json:"name,omitempty"`
	} `json:"filters,omitempty"`

	// IncludePermissionsInfo Include permission information in response.
	IncludePermissionsInfo *bool `json:"includePermissionsInfo,omitempty"`

	// OrderBy Sorting configuration.
	OrderBy *struct {
		// Direction Sorting direction:
		// - `desc` — descending;
		// - `asc` — ascending.
		Direction ListDirectoryArgsOrderByDirection `json:"direction"`

		// Field Field to order by entries:
		// - `createdAt` — date of field creation;
		// - `name` — name of the field.
		Field ListDirectoryArgsOrderByField `json:"field"`
	} `json:"orderBy,omitempty"`

	// Page Page number for pagination.
	Page *float32 `json:"page,omitempty"`

	// PageSize Number of entries per page.
	PageSize *float32 `json:"pageSize,omitempty"`

	// Path Directory path to list entries from.
	Path *string `json:"path,omitempty"`
}

// ListDirectoryArgsCreatedBy0 defines model for .
type ListDirectoryArgsCreatedBy0 = string

// ListDirectoryArgsCreatedBy1 defines model for .
type ListDirectoryArgsCreatedBy1 = []string

// ListDirectoryArgs_CreatedBy Filter entries by creator.
type ListDirectoryArgs_CreatedBy struct {
	union json.RawMessage
}

// ListDirectoryArgsOrderByDirection Sorting direction:
// - `desc` — descending;
// - `asc` — ascending.
type ListDirectoryArgsOrderByDirection string

// ListDirectoryArgsOrderByField Field to order by entries:
// - `createdAt` — date of field creation;
// - `name` — name of the field.
type ListDirectoryArgsOrderByField string

// ListDirectoryBreadCrumb defines model for ListDirectoryBreadCrumb.
type ListDirectoryBreadCrumb struct {
	// EntryId Entry ID of the breadcrumb item.
	EntryId string `json:"entryId"`

	// IsLocked Indicates if the item is locked.
	IsLocked bool `json:"isLocked"`

	// Path Path of the breadcrumb item.
	Path string `json:"path"`

	// Permissions Permissions for the breadcrumb item.
	Permissions struct {
		// Admin Indicates if there are permissions for admin.
		Admin bool `json:"admin"`

		// Edit Indicates if there are permissions to edit.
		Edit bool `json:"edit"`

		// Execute Indicates if there are permissions to execute.
		Execute bool `json:"execute"`

		// Read Indicates if there are permissions to read.
		Read bool `json:"read"`
	} `json:"permissions"`

	// Title Title of the breadcrumb item.
	Title string `json:"title"`
}

// ListDirectoryEntry defines model for ListDirectoryEntry.
type ListDirectoryEntry struct {
	// CollectionId ID of the collection the entry belongs to.
	CollectionId *string `json:"collectionId"`

	// CollectionTitle Collection name.
	CollectionTitle *string `json:"collectionTitle,omitempty"`

	// CreatedAt Creation timestamp.
	CreatedAt string `json:"createdAt"`

	// CreatedBy Creator of the entry.
	CreatedBy string `json:"createdBy"`

	// EntryId Unique identifier of the entry.
	EntryId string `json:"entryId"`

	// Hidden Indicates if the entry is hidden.
	Hidden bool `json:"hidden"`

	// IsFavorite Indicates if the entry is marked as favorite.
	IsFavorite bool `json:"isFavorite"`

	// IsLocked Indicates if the entry is locked.
	IsLocked bool `json:"isLocked"`

	// Key Key identifier of the entry.
	Key string `json:"key"`

	// Meta Metadata associated with the entry.
	Meta *map[string]interface{} `json:"meta"`

	// Name Name of the entry.
	Name string `json:"name"`

	// Permissions Permissions for the entry.
	Permissions *struct {
		// Admin Indicates if there are permissions for admin.
		Admin bool `json:"admin"`

		// Edit Indicates if there are permissions to edit.
		Edit bool `json:"edit"`

		// Execute Indicates if there are permissions to execute.
		Execute bool `json:"execute"`

		// Read Indicates if there are permissions to read.
		Read bool `json:"read"`
	} `json:"permissions,omitempty"`

	// PublishedId Published version ID.
	PublishedId *string `json:"publishedId"`

	// SavedId Saved version ID.
	SavedId string `json:"savedId"`

	// Scope Type of the entry, e.g. `dash` — dashboard, `widget` — chart, etc.
	Scope EntryScope `json:"scope"`

	// Type Type of the entry (e.g., dash, dataset, connection).
	Type string `json:"type"`

	// UpdatedAt Last update timestamp.
	UpdatedAt string `json:"updatedAt"`

	// UpdatedBy Last updater of the entry.
	UpdatedBy string `json:"updatedBy"`

	// WorkbookId ID of the workbook the entry belongs to.
	WorkbookId string `json:"workbookId"`

	// WorkbookTitle Workbook name.
	WorkbookTitle *string `json:"workbookTitle,omitempty"`
}

// ListDirectoryResult defines model for ListDirectoryResult.
type ListDirectoryResult struct {
	// BreadCrumbs Navigation breadcrumbs for the current path.
	BreadCrumbs []ListDirectoryBreadCrumb `json:"breadCrumbs"`

	// Entries List of directory entries.
	Entries []ListDirectoryEntry `json:"entries"`

	// HasNextPage Indicates if there are more pages.
	HasNextPage bool `json:"hasNextPage"`
}

// ApiVersionHeader defines model for ApiVersionHeader.
type ApiVersionHeader string

// iAMTokenContextKey is the context key for IAM token security scheme
type iAMTokenContextKey string

// organizationIDContextKey is the context key for Organization ID security scheme
type organizationIDContextKey string

// PostRpcGetEntriesParams defines parameters for PostRpcGetEntries.
type PostRpcGetEntriesParams struct {
	// XDlApiVersion API version header.
	XDlApiVersion PostRpcGetEntriesParamsXDlApiVersion `json:"x-dl-api-version"`
	XDlAuditMode  *PostRpcGetEntriesParamsXDlAuditMode `json:"x-dl-audit-mode,omitempty"`
}

// PostRpcGetEntriesParamsXDlApiVersion defines parameters for PostRpcGetEntries.
type PostRpcGetEntriesParamsXDlApiVersion string

// PostRpcGetEntriesParamsXDlAuditMode defines parameters for PostRpcGetEntries.
type PostRpcGetEntriesParamsXDlAuditMode string

// PostRpcListDirectoryParams defines parameters for PostRpcListDirectory.
type PostRpcListDirectoryParams struct {
	// XDlApiVersion API version header.
	XDlApiVersion PostRpcListDirectoryParamsXDlApiVersion `json:"x-dl-api-version"`
}

// PostRpcListDirectoryParamsXDlApiVersion defines parameters for PostRpcListDirectory.
type PostRpcListDirectoryParamsXDlApiVersion string

// PostRpcGetEntriesJSONRequestBody defines body for PostRpcGetEntries for application/json ContentType.
type PostRpcGetEntriesJSONRequestBody = GetEntriesV2Args

// PostRpcListDirectoryJSONRequestBody defines body for PostRpcListDirectory for application/json ContentType.
type PostRpcListDirectoryJSONRequestBody = ListDirectoryArgs

// AsGetEntriesV2ResultEntries0 returns the union data inside the GetEntriesV2Result_Entries_Item as a GetEntriesV2ResultEntries0
func (t GetEntriesV2Result_Entries_Item) AsGetEntriesV2ResultEntries0() (GetEntriesV2ResultEntries0, error) {
	var body GetEntriesV2ResultEntries0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetEntriesV2ResultEntries0 overwrites any union data inside the GetEntriesV2Result_Entries_Item as the provided GetEntriesV2ResultEntries0
func (t *GetEntriesV2Result_Entries_Item) FromGetEntriesV2ResultEntries0(v GetEntriesV2ResultEntries0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetEntriesV2ResultEntries0 performs a merge with any union data inside the GetEntriesV2Result_Entries_Item, using the provided GetEntriesV2ResultEntries0
func (t *GetEntriesV2Result_Entries_Item) MergeGetEntriesV2ResultEntries0(v GetEntriesV2ResultEntries0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGetEntriesV2ResultEntries1 returns the union data inside the GetEntriesV2Result_Entries_Item as a GetEntriesV2ResultEntries1
func (t GetEntriesV2Result_Entries_Item) AsGetEntriesV2ResultEntries1() (GetEntriesV2ResultEntries1, error) {
	var body GetEntriesV2ResultEntries1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetEntriesV2ResultEntries1 overwrites any union data inside the GetEntriesV2Result_Entries_Item as the provided GetEntriesV2ResultEntries1
func (t *GetEntriesV2Result_Entries_Item) FromGetEntriesV2ResultEntries1(v GetEntriesV2ResultEntries1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGetEntriesV2ResultEntries1 performs a merge with any union data inside the GetEntriesV2Result_Entries_Item, using the provided GetEntriesV2ResultEntries1
func (t *GetEntriesV2Result_Entries_Item) MergeGetEntriesV2ResultEntries1(v GetEntriesV2ResultEntries1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetEntriesV2Result_Entries_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetEntriesV2Result_Entries_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsListDirectoryArgsCreatedBy0 returns the union data inside the ListDirectoryArgs_CreatedBy as a ListDirectoryArgsCreatedBy0
func (t ListDirectoryArgs_CreatedBy) AsListDirectoryArgsCreatedBy0() (ListDirectoryArgsCreatedBy0, error) {
	var body ListDirectoryArgsCreatedBy0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListDirectoryArgsCreatedBy0 overwrites any union data inside the ListDirectoryArgs_CreatedBy as the provided ListDirectoryArgsCreatedBy0
func (t *ListDirectoryArgs_CreatedBy) FromListDirectoryArgsCreatedBy0(v ListDirectoryArgsCreatedBy0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListDirectoryArgsCreatedBy0 performs a merge with any union data inside the ListDirectoryArgs_CreatedBy, using the provided ListDirectoryArgsCreatedBy0
func (t *ListDirectoryArgs_CreatedBy) MergeListDirectoryArgsCreatedBy0(v ListDirectoryArgsCreatedBy0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsListDirectoryArgsCreatedBy1 returns the union data inside the ListDirectoryArgs_CreatedBy as a ListDirectoryArgsCreatedBy1
func (t ListDirectoryArgs_CreatedBy) AsListDirectoryArgsCreatedBy1() (ListDirectoryArgsCreatedBy1, error) {
	var body ListDirectoryArgsCreatedBy1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListDirectoryArgsCreatedBy1 overwrites any union data inside the ListDirectoryArgs_CreatedBy as the provided ListDirectoryArgsCreatedBy1
func (t *ListDirectoryArgs_CreatedBy) FromListDirectoryArgsCreatedBy1(v ListDirectoryArgsCreatedBy1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListDirectoryArgsCreatedBy1 performs a merge with any union data inside the ListDirectoryArgs_CreatedBy, using the provided ListDirectoryArgsCreatedBy1
func (t *ListDirectoryArgs_CreatedBy) MergeListDirectoryArgsCreatedBy1(v ListDirectoryArgsCreatedBy1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ListDirectoryArgs_CreatedBy) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ListDirectoryArgs_CreatedBy) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
